hide all
unset dynamic_measures
show cartoon, all
color grey, all
run draw_links.py
draw_links resi 1 and name CA and Chain A, resi 6 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=1:6_greenAA
draw_links resi 1 and name CA and Chain A, resi 40 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=1:40redAA
draw_links resi 1 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=1:59_greenAA
draw_links resi 1 and name CA and Chain A, resi 60 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=1:60_greenAA
draw_links resi 2 and name CA and Chain A, resi 4 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:4_greenAA
draw_links resi 2 and name CA and Chain A, resi 5 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:5_greenAA
draw_links resi 2 and name CA and Chain A, resi 6 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:6_greenAA
draw_links resi 2 and name CA and Chain A, resi 34 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:34_greenAA
draw_links resi 2 and name CA and Chain A, resi 37 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:37_greenAA
draw_links resi 2 and name CA and Chain A, resi 39 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:39_greenAA
draw_links resi 2 and name CA and Chain A, resi 40 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:40_greenAA
draw_links resi 2 and name CA and Chain A, resi 41 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:41_greenAA
draw_links resi 2 and name CA and Chain A, resi 45 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:45_greenAA
draw_links resi 2 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:48_greenAA
draw_links resi 2 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:59_greenAA
draw_links resi 2 and name CA and Chain A, resi 60 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:60_greenAA
draw_links resi 2 and name CA and Chain A, resi 61 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:61_greenAA
draw_links resi 2 and name CA and Chain A, resi 62 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=2:62_greenAA
draw_links resi 3 and name CA and Chain A, resi 6 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=3:6_greenAA
draw_links resi 3 and name CA and Chain A, resi 7 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=3:7redAA
draw_links resi 3 and name CA and Chain A, resi 40 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=3:40redAA
draw_links resi 4 and name CA and Chain A, resi 6 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=4:6_greenAA
draw_links resi 4 and name CA and Chain A, resi 7 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=4:7redAA
draw_links resi 5 and name CA and Chain A, resi 7 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=5:7redAA
draw_links resi 5 and name CA and Chain A, resi 9 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=5:9redAA
draw_links resi 5 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=5:59_greenAA
draw_links resi 6 and name CA and Chain A, resi 8 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=6:8_greenAA
draw_links resi 6 and name CA and Chain A, resi 10 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=6:10_greenAA
draw_links resi 6 and name CA and Chain A, resi 20 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=6:20_greenAA
draw_links resi 6 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=6:31_greenAA
draw_links resi 6 and name CA and Chain A, resi 34 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=6:34_greenAA
draw_links resi 6 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=6:48_greenAA
draw_links resi 6 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=6:52_greenAA
draw_links resi 6 and name CA and Chain A, resi 54 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=6:54_greenAA
draw_links resi 6 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=6:59_greenAA
draw_links resi 7 and name CA and Chain A, resi 9 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=7:9redAA
draw_links resi 7 and name CA and Chain A, resi 11 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=7:11redAA
draw_links resi 7 and name CA and Chain A, resi 17 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=7:17redAA
draw_links resi 7 and name CA and Chain A, resi 35 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=7:35redAA
draw_links resi 8 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=8:52_greenAA
draw_links resi 9 and name CA and Chain A, resi 11 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=9:11redAA
draw_links resi 9 and name CA and Chain A, resi 12 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=9:12redAA
draw_links resi 9 and name CA and Chain A, resi 13 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=9:13redAA
draw_links resi 9 and name CA and Chain A, resi 15 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=9:15redAA
draw_links resi 9 and name CA and Chain A, resi 53 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=9:53redAA
draw_links resi 9 and name CA and Chain A, resi 58 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=9:58redAA
draw_links resi 10 and name CA and Chain A, resi 20 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=10:20_greenAA
draw_links resi 10 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=10:31_greenAA
draw_links resi 10 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=10:52_greenAA
draw_links resi 11 and name CA and Chain A, resi 13 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=11:13_greenAA
draw_links resi 11 and name CA and Chain A, resi 15 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=11:15_greenAA
draw_links resi 12 and name CA and Chain A, resi 14 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=12:14redAA
draw_links resi 12 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=12:52_greenAA
draw_links resi 13 and name CA and Chain A, resi 15 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=13:15_greenAA
draw_links resi 13 and name CA and Chain A, resi 20 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=13:20_greenAA
draw_links resi 13 and name CA and Chain A, resi 51 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=13:51_greenAA
draw_links resi 13 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=13:52_greenAA
draw_links resi 14 and name CA and Chain A, resi 16 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=14:16redAA
draw_links resi 14 and name CA and Chain A, resi 20 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=14:20_greenAA
draw_links resi 15 and name CA and Chain A, resi 18 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=15:18_greenAA
draw_links resi 15 and name CA and Chain A, resi 20 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=15:20_greenAA
draw_links resi 15 and name CA and Chain A, resi 21 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=15:21_greenAA
draw_links resi 15 and name CA and Chain A, resi 51 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=15:51_greenAA
draw_links resi 15 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=15:52_greenAA
draw_links resi 16 and name CA and Chain A, resi 20 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=16:20_greenAA
draw_links resi 17 and name CA and Chain A, resi 20 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=17:20_greenAA
draw_links resi 17 and name CA and Chain A, resi 30 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=17:30redAA
draw_links resi 17 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=17:31_greenAA
draw_links resi 17 and name CA and Chain A, resi 32 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=17:32redAA
draw_links resi 17 and name CA and Chain A, resi 35 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=17:35redAA
draw_links resi 18 and name CA and Chain A, resi 20 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=18:20_greenAA
draw_links resi 18 and name CA and Chain A, resi 21 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=18:21_greenAA
draw_links resi 18 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=18:31_greenAA
draw_links resi 19 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=19:31_greenAA
draw_links resi 20 and name CA and Chain A, resi 22 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:22_greenAA
draw_links resi 20 and name CA and Chain A, resi 23 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:23_greenAA
draw_links resi 20 and name CA and Chain A, resi 24 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:24_greenAA
draw_links resi 20 and name CA and Chain A, resi 25 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:25_greenAA
draw_links resi 20 and name CA and Chain A, resi 26 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:26_greenAA
draw_links resi 20 and name CA and Chain A, resi 28 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:28_greenAA
draw_links resi 20 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:31_greenAA
draw_links resi 20 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:48_greenAA
draw_links resi 20 and name CA and Chain A, resi 51 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:51_greenAA
draw_links resi 20 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=20:52_greenAA
draw_links resi 21 and name CA and Chain A, resi 24 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=21:24_greenAA
draw_links resi 21 and name CA and Chain A, resi 26 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=21:26_greenAA
draw_links resi 21 and name CA and Chain A, resi 27 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=21:27_greenAA
draw_links resi 21 and name CA and Chain A, resi 29 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=21:29_greenAA
draw_links resi 21 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=21:31_greenAA
draw_links resi 22 and name CA and Chain A, resi 24 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=22:24_greenAA
draw_links resi 22 and name CA and Chain A, resi 25 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=22:25redAA
draw_links resi 23 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=23:48_greenAA
draw_links resi 23 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=23:52_greenAA
draw_links resi 24 and name CA and Chain A, resi 26 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=24:26_greenAA
draw_links resi 24 and name CA and Chain A, resi 30 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=24:30_greenAA
draw_links resi 24 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=24:31_greenAA
draw_links resi 24 and name CA and Chain A, resi 44 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=24:44_greenAA
draw_links resi 24 and name CA and Chain A, resi 47 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=24:47_greenAA
draw_links resi 24 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=24:48_greenAA
draw_links resi 24 and name CA and Chain A, resi 50 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=24:50_greenAA
draw_links resi 24 and name CA and Chain A, resi 51 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=24:51_greenAA
draw_links resi 24 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=24:52_greenAA
draw_links resi 25 and name CA and Chain A, resi 30 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=25:30redAA
draw_links resi 26 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=26:31_greenAA
draw_links resi 26 and name CA and Chain A, resi 34 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=26:34_greenAA
draw_links resi 26 and name CA and Chain A, resi 44 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=26:44_greenAA
draw_links resi 26 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=26:48_greenAA
draw_links resi 27 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=27:31_greenAA
draw_links resi 28 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=28:31_greenAA
draw_links resi 28 and name CA and Chain A, resi 32 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=28:32redAA
draw_links resi 29 and name CA and Chain A, resi 31 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=29:31_greenAA
draw_links resi 29 and name CA and Chain A, resi 32 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=29:32redAA
draw_links resi 30 and name CA and Chain A, resi 32 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=30:32redAA
draw_links resi 30 and name CA and Chain A, resi 42 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=30:42redAA
draw_links resi 31 and name CA and Chain A, resi 33 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=31:33_greenAA
draw_links resi 31 and name CA and Chain A, resi 34 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=31:34_greenAA
draw_links resi 31 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=31:48_greenAA
draw_links resi 32 and name CA and Chain A, resi 35 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=32:35redAA
draw_links resi 32 and name CA and Chain A, resi 38 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=32:38redAA
draw_links resi 33 and name CA and Chain A, resi 42 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=33:42redAA
draw_links resi 34 and name CA and Chain A, resi 36 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=34:36_greenAA
draw_links resi 34 and name CA and Chain A, resi 38 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=34:38_greenAA
draw_links resi 34 and name CA and Chain A, resi 39 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=34:39_greenAA
draw_links resi 34 and name CA and Chain A, resi 44 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=34:44_greenAA
draw_links resi 34 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=34:48_greenAA
draw_links resi 35 and name CA and Chain A, resi 37 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=35:37redAA
draw_links resi 37 and name CA and Chain A, resi 40 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=37:40redAA
draw_links resi 38 and name CA and Chain A, resi 40 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=38:40redAA
draw_links resi 39 and name CA and Chain A, resi 42 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=39:42redAA
draw_links resi 40 and name CA and Chain A, resi 42 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=40:42redAA
draw_links resi 41 and name CA and Chain A, resi 45 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=41:45_greenAA
draw_links resi 42 and name CA and Chain A, resi 47 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=42:47redAA
draw_links resi 43 and name CA and Chain A, resi 45 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=43:45_greenAA
draw_links resi 44 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=44:48_greenAA
draw_links resi 44 and name CA and Chain A, resi 49 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=44:49_greenAA
draw_links resi 44 and name CA and Chain A, resi 51 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=44:51_greenAA
draw_links resi 45 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=45:48_greenAA
draw_links resi 45 and name CA and Chain A, resi 49 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=45:49_greenAA
draw_links resi 45 and name CA and Chain A, resi 56 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=45:56_greenAA
draw_links resi 45 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=45:59_greenAA
draw_links resi 45 and name CA and Chain A, resi 60 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=45:60_greenAA
draw_links resi 46 and name CA and Chain A, resi 48 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=46:48_greenAA
draw_links resi 46 and name CA and Chain A, resi 50 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=46:50redAA
draw_links resi 48 and name CA and Chain A, resi 50 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=48:50_greenAA
draw_links resi 48 and name CA and Chain A, resi 51 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=48:51_greenAA
draw_links resi 48 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=48:52_greenAA
draw_links resi 48 and name CA and Chain A, resi 54 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=48:54_greenAA
draw_links resi 48 and name CA and Chain A, resi 56 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=48:56_greenAA
draw_links resi 48 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=48:59_greenAA
draw_links resi 49 and name CA and Chain A, resi 51 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=49:51_greenAA
draw_links resi 49 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=49:52_greenAA
draw_links resi 49 and name CA and Chain A, resi 54 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=49:54_greenAA
draw_links resi 49 and name CA and Chain A, resi 56 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=49:56_greenAA
draw_links resi 49 and name CA and Chain A, resi 58 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=49:58_greenAA
draw_links resi 49 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=49:59_greenAA
draw_links resi 49 and name CA and Chain A, resi 60 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=49:60_greenAA
draw_links resi 50 and name CA and Chain A, resi 52 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=50:52_greenAA
draw_links resi 50 and name CA and Chain A, resi 54 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=50:54_greenAA
draw_links resi 50 and name CA and Chain A, resi 56 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=50:56_greenAA
draw_links resi 51 and name CA and Chain A, resi 54 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=51:54_greenAA
draw_links resi 52 and name CA and Chain A, resi 54 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=52:54_greenAA
draw_links resi 52 and name CA and Chain A, resi 55 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=52:55_greenAA
draw_links resi 52 and name CA and Chain A, resi 58 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=52:58_greenAA
draw_links resi 52 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=52:59_greenAA
draw_links resi 54 and name CA and Chain A, resi 56 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=54:56_greenAA
draw_links resi 54 and name CA and Chain A, resi 58 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=54:58_greenAA
draw_links resi 54 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=54:59_greenAA
draw_links resi 54 and name CA and Chain A, resi 62 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=54:62_greenAA
draw_links resi 55 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=55:59_greenAA
draw_links resi 56 and name CA and Chain A, resi 58 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=56:58_greenAA
draw_links resi 56 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=56:59_greenAA
draw_links resi 56 and name CA and Chain A, resi 60 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=56:60_greenAA
draw_links resi 56 and name CA and Chain A, resi 61 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=56:61_greenAA
draw_links resi 57 and name CA and Chain A, resi 59 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=57:59_greenAA
draw_links resi 57 and name CA and Chain A, resi 61 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=57:61redAA
draw_links resi 57 and name CA and Chain A, resi 62 and name CA and Chain A, color=red, color2=red, radius=0.05, object_name=57:62redAA
draw_links resi 58 and name CA and Chain A, resi 60 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=58:60_greenAA
draw_links resi 59 and name CA and Chain A, resi 61 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=59:61_greenAA
draw_links resi 59 and name CA and Chain A, resi 62 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=59:62_greenAA
draw_links resi 60 and name CA and Chain A, resi 62 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=60:62_greenAA
draw_links resi 60 and name CA and Chain A, resi 63 and name CA and Chain A, color=green, color2=green, radius=0.05, object_name=60:63_greenAA
select ligand, organic
select inorganiclig, inorganic
show spheres, inorganiclig
show sticks, ligand
color yellow, ligand
color magenta, inorganiclig
zoom all
hide labels
